"""Constants used in rate model."""
KRORW = "krorw"
SWCR = "swcr"
SOWCR = "sowcr"
KRO = "kro"
KRW = "krw"
SAT_COL = "saturation"
SWL = "swl"
KROLW = "krolw"
KRWR = "krwr"
SWU = "swu"
KRWU = "krwu"

DATE_COL = "date"
WELL_COL = "well"
INJT_COL = "injt"
PRES_COL = "pres"
QOIL_COL = "qoil"
QWAT_COL = "qwat"
QGAS_COL = "qgas"
QLIQ_COL = "qliq"
WBHP_COL = "bhp"
WCT_COL = "wct"
GOR_COL = "gor"
MODL_COL = "model"
SCEN_COL = "scenario"
